### ISSUE TITLE
eigenvectors in dynaRespTD

### ISSUE THREAD

**Issue by JaehwanJeon** [ECheynet/dynaRespTD#1]
Hi, this Jaehwan Jeon.
I've seen your dynaRespTD code and found something that I couldn't quite understand.
In line 101, it is seen that you constructed modal mass matrix using phi0_N, which is a normalized eigenvector matrix.
However, in lines 197 and 198, it can be seen that phi0 (not normalized eigenvector matrix) was used to transform coordinates.
Is this an error? Thank you.

**Comment by ECheynet** [comment]
Dear Jaehwan Jeon,

Thank you for your message!

This is a very good question. Maybe a little tricky to reply. So in short: there is  likely no error in the calculation of the response. Maybe it's more a "poor notation" due to an earlier correction that I will elaborate on herein.  The use of phi0 and phi0_N is mainly due to the interaction between cable motion and deck motion for the lateral bridge response. If the cable motion is neglected, phi0 and phi0_N become identical.

To some extent, the modes phi0 are already normalized. When the deck motion is larger than the cable motion, the modes phi0 have a maximum of 1. If the motion of the cables dominates over the motion of the deck, some maxima of phi0 are lower than 1 because the mode shapes of the deck are normalized by the mode shapes of the cables. This is the case for some of the lateral modes (I think it was HS2 and HA2).


The variable phi0_N forces all the modes to have a maximal value of 1.

Initially, I was using phi0_N for all the mode shapes. According to the full-scale measurements, it seems it was incorrect to do so for the mode shapes dominated by the cable motion. Indeed, I was overestimating the response of these modes in a previous study ([here](https://windengineeringuis.github.io/papers/Cheynet2016c.pdf), in the top panel of Fig 15, the modes HS2 and HA2 are too large compared to the measured response). Note that I am not 100% sure that the lower-than-expected amplitudes of HA2 and HS2 are due to the cable motion, but that is the most probable reason I have found from the modal analysis.

I enclose a picture of the lateral power spectral density of the bridge lateral response using either phi0_N or phi0. The main difference is near modes HS2 and HA2 [(picture).](https://github.com/ECheynet/dynaRespTD/files/7905177/test.pdf)
